### ISSUE TITLE
failure to build with boost 1.56.0

### ISSUE THREAD

**Issue by ht990332** [jthornber/thin-provisioning-tools#18]
While compiling thin-provisioning-tools from 0.4.0 tag with boost 1.56.0 installed, I get the following error:
    [DEP] thin-provisioning/thin_delta.cc
    [CXX] thin-provisioning/thin_dump.cc
    [DEP] thin-provisioning/thin_dump.cc
    [CXX] thin-provisioning/thin_metadata_size.cc
    [DEP] thin-provisioning/thin_metadata_size.cc
    [CXX] thin-provisioning/thin_pool.cc
    [DEP] thin-provisioning/thin_pool.cc
    [CXX] thin-provisioning/thin_repair.cc
    [DEP] thin-provisioning/thin_repair.cc
    [CXX] thin-provisioning/thin_restore.cc
    [DEP] thin-provisioning/thin_restore.cc
    [CXX] thin-provisioning/thin_rmap.cc
    [DEP] thin-provisioning/thin_rmap.cc
    [CXX] thin-provisioning/xml_format.cc
    [DEP] thin-provisioning/xml_format.cc
    [LD]  bin/pdata_tools
thin-provisioning/human_readable_format.o: In function `begin_superblock':
/home/hussam/packages/thin-provisioning-tools/trunk/src/thin-provisioning-tools-0.4.0/thin-provisioning/human_readable_format.cc:47: undefined reference to`std::basic_ostream<char, std::char_traits<char> >& boost::operator<< <char, std::char_traits<char>, unsigned long>(std::basic_ostream<char, std::char_traits<char> >&, boost::optional<unsigned long> const&)'
collect2: error: ld returned 1 exit status
Makefile:139: recipe for target 'bin/pdata_tools' failed
make: **\* [bin/pdata_tools] Error 1

**Comment by pmachata** [comment]
I think the correct way to fix this is to include boost/optional/optional_io.hpp.  Sometime after 1.55, boost introduced a forward declaration of operator<< in optional.hpp.  In 1.55 and earlier, when << was used without the _io having been included, what got dumped was an implicit bool conversion.  Consider:

```
$ cat opt.cc
#include <boost/optional/optional.hpp>
int main () {
  std::cout << boost::optional <int> () << boost::optional <int> (7) << std::endl;
}
$ g++ opt.cc
$ ./a.out 
01
```
Versus:
```
$ cat opt.cc
#include <boost/optional/optional_io.hpp>
int main () {
  std::cout << boost::optional <int> () << boost::optional <int> (7) << std::endl;
}
$ g++ opt.cc
$ ./a.out 
-- 7
```

**Comment by jthornber** [comment]
I didn't know that.  Thanks.

I'm unable to test this set up however.  Hussam are you interested in
testing?

**Comment by hussamT** [comment]
I reverted the previous fix and instead included boost/optional/optional_io.hpp
It compiles correctly. Thank you.

**Comment by jthornber** [comment]
Great, I'll push that change.
