### ISSUE TITLE
Missing include after 733c7df

### ISSUE THREAD

**Issue by asavah** [jthornber/thin-provisioning-tools#122]
Build fails after 733c7df
```
thin-provisioning/metadata_dumper.cc:21:10: fatal error: persistent-data/space-maps/noop.h: No such file or directory
 #include "persistent-data/space-maps/noop.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
persistent-data/space-maps/noop.h does not exist.

**Comment by jthornber** [comment]
Thanks for spotting this.  Should be fixed now.
